### ISSUE TITLE
Error when using Commerce Admin Orders v2.4.2 & Craft Commerce v2.1.11

### ISSUE THREAD

**Issue by hegrobler** [KuriousAgency/commerce-admin-orders#11]
See screenshot for an error that occurs when using Commerce Admin Order v2.4.2 on Craft Commerce v2.1.11 - I've downgraded to Commerce v2.1.10 & that has temporarily resolved it for me. 

![Capture](https://user-images.githubusercontent.com/354816/62867167-ef198980-bd12-11e9-818a-47ed4922ada7.PNG)

**Comment by samuelbirch** [comment]
thanks, we'll take a look.

**Comment by samuelbirch** [comment]
looks like a bug introduced in commerce 2.1.11. 
I've created a pull request to fix the issue: https://github.com/craftcms/commerce/pull/961

**Comment by samuelbirch** [comment]
this has been merged now in Commerce 2.1.12.
