### ISSUE TITLE
Errors with fresh install

### ISSUE THREAD

**Issue by maxwellhibbert** [KuriousAgency/commerce-admin-orders#14]
I just installed Craft and tried your plugin out, but I'm getting errors when adding items to an order. Here's the output:

<img width="1437" alt="order_error" src="https://user-images.githubusercontent.com/2948524/65188128-076a8a00-dab1-11e9-95b6-9bb92869d077.png">

Craft Commerce 2.1.13
Craft 3.3.4.1

**Comment by samuelbirch** [comment]
Please give version 2.5.2 and let me know if this fixes your issue.
