### ISSUE TITLE
#transactionsTab Opens in a new window

### ISSUE THREAD

**Issue by dwhoban** [KuriousAgency/commerce-admin-orders#16]
When I try to complete an New order via the admin panel I cannot get past the shipping screen.

When clicking continue on this screen I get the #transactionsTab opening in a new browser tab and the order closes in the original one

The new is blank and loads no html.

The only error flagged is:

```
TypeError: r.shift is not a function jquery.js:5481:26
    jQuery 3
        handler
        dispatch
        handle
```

**Comment by mikeymeister** [comment]
Hi @dwhoban what versions of craft and craft commerce are you using? Also, what os and browser are you experiencing this error on?

**Comment by dwhoban** [comment]
Browser: Firefox, Chrome & Safari
OS: MacOS Catalina and Windows 10
Craft 3.3.5 & 3.3.6
Commerce: 2.1.13

**Comment by mikeymeister** [comment]
I've been unable to replicate this problem so far. Are you able to send a copy/the contents of your composer file?

**Comment by dwhoban** [comment]
Caused by a plugin conflict with [Xero plugin](https://github.com/mediabeastnz/craft-commerce-xero/issues/3) which is now resolved.
