### ISSUE TITLE
Issue adding products to cart commerce 2.2

### ISSUE THREAD

**Issue by MaximilianSchwarz** [KuriousAgency/commerce-admin-orders#17]
Hello,

if i want to create a new order via the backend and add one product the loading icon is stuck and no product is added to the cart.

I use the Craft CMS 3.3.13 and Craft Commerce 2.2.6.

Can you fixed this issue?

**Comment by mcjackson18** [comment]
Hey @MaximilianSchwarz, leave this with us.

**Comment by MaximilianSchwarz** [comment]
If i click at the add button i got the following error:

admin/commerce-admin-orders/orders/products: 500 Error
`{"error":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dateCreated' cannot be null\nThe SQL being executed was: UPDATE `commerce_lineitems` SET `orderId`=144849, `purchasableId`=98987, `price`='2715', `saleAmount`='0', `salePrice`='2715', `weight`='0', `height`='0', `length`='0', `width`='0', `subtotal`='2715', `total`='2715', `dateCreated`=NULL, `dateUpdated`='2019-10-29 09:23:47' WHERE `id`=574"}`

**Comment by mcjackson18** [comment]
@MaximilianSchwarz this is now fixed in 2.5.4
