### ISSUE TITLE
FR State select dropdown is US-centric

### ISSUE THREAD

**Issue by peteeveleigh** [KuriousAgency/commerce-admin-orders#18]
The State select element when creating an order lists only US states with no option to enter an alternative.

Is it possible to either change the list or make it a straightforward text input?

**Comment by mcjackson18** [comment]
@fantasticmachine, the states list is populated from the states that are setup in Commerce, further details can be found here - https://craftcms.com/docs/commerce/3.x/countries-states.html.

Alternatively, if you start typing the name in state field and it doesn't exist, you will be given the option to add the new state.
