### ISSUE TITLE
Custom CP trigger error because of hard coded /admin trigger

### ISSUE THREAD

**Issue by srosenbrand** [KuriousAgency/commerce-admin-orders#2]
When using a custom CP trigger in the Craft general config file the 'New order' button throws an template not found error because of hardcoded /admin path.

In file:
/vendor/kuriousagency/commerce-admin-orders/src/assetbundles/ordersnew/dist/js/Orders.js

Line 56: 
var $iframe = $('<iframe src="/admin/commerce-admin-orders/orders/new" style="width:100%; height:100%;"></iframe>').appendTo($container);

**Comment by samuelbirch** [comment]
Fixed in version 2.2.9.

**Comment by Moorst** [comment]
Don't think it is fixed - I'm getting the same issue with 2.2.9.

I'm getting the modal which prompts you to choose a user, though when clicking continue the error is thrown;

![image](https://user-images.githubusercontent.com/6151408/56996887-de973600-6b9d-11e9-8c20-f8ec428bb262.png)

**Comment by samuelbirch** [comment]
ok, thanks. We'll take a look.

**Comment by samuelbirch** [comment]
ok, this should be fixed with version 2.2.10
