### ISSUE TITLE
It doesn't work with Craft 3.4

### ISSUE THREAD

**Issue by superpikar** [KuriousAgency/commerce-admin-orders#24]
Hi, I upgrade my craft to the latest one, your plugin doesn't work. An error appear after the `order admin modal` is displayed

Version
Craft : 3.4.5
Commerce : 2.2.17

![image](https://user-images.githubusercontent.com/2832280/74581316-a9e75480-4fe0-11ea-875c-684d585a6920.png)

**Comment by superpikar** [comment]
It probably doesn't work with commerce 3 as well.
I am now downgrading to Craft 3.3 version

Any plan to fixed this issue? So a new user able to use your plugin on Craft 3.4 and Commerce 3

FYI, Craft Commerce 3 now support create order via admin, but it's only for **Commerce Pro** version

**Comment by superpikar** [comment]
Downgrading process itself is not easy, need to restore previous database backup.
would be better if your plugin support craft 3.4 and commerce 3 in the near future 😊 

https://github.com/craftcms/cms/issues/4527

**Comment by mcjackson18** [comment]
Hi @superpikar, support for Craft 3.4 has been added in version 2.6.3. Support for Commerce 3 is on the roadmap.

**Comment by JustJarethB** [comment]
@mcjackson18 Any target release date for commerce 3 support yet?

Cheers

**Comment by mposborne** [comment]
Any update on commerce 3 support yet?

**Comment by mcjackson18** [comment]
Version 2.7.0 now supports Commerce 3.
