### ISSUE TITLE
No support for Commerce 3?

### ISSUE THREAD

**Issue by bartrylant** [KuriousAgency/commerce-admin-orders#25]
Am I correct that this plugin does not work with Commerce 3? I'd like to use it as the interface is much simpler than the default Commerce "new order" interface, but composer won't let me install when I am running Commerce 3.

**Comment by mcjackson18** [comment]
@bartrylant, that's correct, the plugin at the moment doesn't support Commerce 3 we wanted to see how the admin orders in Commerce progressed before making any changes.

We've now had a few people mention they'd prefer to use the plugin so we're looking into the best way to make this work.

**Comment by bartrylant** [comment]
Yes, please do. The native way of doing this with Commerce is much too cluttered and complicated. I would use this in the brick-store from the webshop, where the owner has a barcode scanner that can enter the sku code in the search field. Jut scan and add, scan and add,…

Only one feature request I would still have is to add a field to change the total price.

**Comment by mcjackson18** [comment]
@bartrylant, Commerce 3 support has been added to version 2.7.0, new orders now use the admin orders modal for creating orders. We've made the decision to remove the edit order feature as Commerce 3 allows you to edit orders. The total price for an order can be adjusted using Commerce 3's order editing.
