### ISSUE TITLE
Issues with version for Commerce 3

### ISSUE THREAD

**Issue by bartrylant** [KuriousAgency/commerce-admin-orders#26]
When I click "new order", I get the popup as it should.

When I click on search by zip code, I get an error:

```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'studioaimee.orders.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

Another error when I try to do a guest checkout:

```
PHP Notice – yii\base\ErrorException
Trying to access array offset on value of type null

$userId = Craft::$app->getRequest()->getBodyParam('userId')[0];
```

Selecting an exisiting user works fine

**Comment by mcjackson18** [comment]
@bartrylant, 2.7.1 should fix these issues, please can you test and confirm.

**Comment by mcjackson18** [comment]
@bartrylant, 2.7.1 should fix these issues, please can you test and confirm.

**Comment by bartrylant** [comment]
The guest user option now works, the zip code search does not.

**Comment by bartrylant** [comment]
It seems to work if I change something in my mysql config.

**Comment by mcjackson18** [comment]
@bartrylant, yes removing the "only_full_group_by" from your MySQL mode will fix this.
