### ISSUE TITLE
FR: set default amount to 1

### ISSUE THREAD

**Issue by bartrylant** [KuriousAgency/commerce-admin-orders#27]
When searching for an item, it would be nice if the quantity field would be 1 by default, instead of empty. From a usability point of view: most of the times someone will want to add 1 of the selected item to the cart. "Nothing" will never be the case. So adding a 1 as a default value will save the user some clicks and useless typing.

**Comment by mcjackson18** [comment]
Thanks for the suggestion, this had been added to 2.7.1.
