### ISSUE TITLE
Modal trigger issue (Commerce > Orders)

### ISSUE THREAD

**Issue by cole007** [KuriousAgency/commerce-admin-orders#29]
We have recently installed this plugin on a client site and clicking on any of the filtering buttons on the Commerce > Orders triggers the New Order modal, overriding the built-in Craft functionality needed to filter Orders.

Craft CMS 3.6.10
Craft Commerce 3.2.17.3
Commerce Admin Orders 2.7.1

It looks like the JS trigger needs updating: `/src/assetbundles/neworder/dist/js/Modal.js:20`

Was:

```
this.$newOrder = $('#header .btn');
```

Should be:

```
this.$newOrder = $('#header .btn.add');
```

Cole

**Comment by mcjackson18** [comment]
Hi @cole007, this is now fixed in version 2.7.2.
