### ISSUE TITLE
FR: new address country

### ISSUE THREAD

**Issue by cole007** [KuriousAgency/commerce-admin-orders#30]
Currently when adding a new address via this plugin the countries and state dropdowns show all possible options.

It would be useful if these could be limited to those enabled within Craft Commerce (we have had a customer accidentally create an order with an address in Afghanistan which threw the tax and shipping out).

**Comment by cole007** [comment]
Just wondering on thoughts regarding this - have marked as FR but equally could be considered a bug (well, by our client at least)

**Comment by mcjackson18** [comment]
Hi @cole007, this is now fixed in version 2.7.3
