### ISSUE TITLE
Products not loading in modal

### ISSUE THREAD

**Issue by cole007** [KuriousAgency/commerce-admin-orders#31]
Using the Craft Commerce Admin Orders plugin and for some reason (perhaps an underlying Craft update) the generated modal is no longer returning products.

Network console not throwing errors. Just an empty (200) response to the `actions/element-indexes/get-elements` POST query:

**Payload:**

```
criteria: {siteId: 1, search: null, offset: 0, limit: 100, status: null}
elementType: "kuriousagency\\commerce\\adminorders\\elements\\Variant"
viewState: {mode: "table", order: "title", sort: "desc"}
paginated: 0
source: *
disabledElementIds: []
context: ""
```

Craft 3.7.16
Craft Commerce 3.4.4
Commerce Admin Orders 2.7.2

Cheers,

Cole

**Comment by mcjackson18** [comment]
Hi @cole007, this is now fixed in version 2.7.3.
