### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by MaximilianSchwarz** [KuriousAgency/commerce-admin-orders#4]
If i want to create a new backend order and i click on new order. After that i choose a customer and click next. I got the following error:

Trying to get property of non-object

I used the Craft CMS 3.2.2.
In the attachment you can see a screenshot.
![Bildschirmfoto 2019-07-16 um 13 51 41](https://user-images.githubusercontent.com/15785801/61292298-260e8500-a7d1-11e9-8acb-727003072508.png)

**Comment by samuelbirch** [comment]
Hi,

What version of commerce have you got installed?

**Comment by MaximilianSchwarz** [comment]
I used the newest one. It's the Version 2.4.0

**Comment by samuelbirch** [comment]
Sorry, what version of craft commerce do you have installed?

**Comment by MaximilianSchwarz** [comment]
Also the newest one 2.1.10

**Comment by samuelbirch** [comment]
can you send your log file please or the stack trace of that issue.

**Comment by MaximilianSchwarz** [comment]
Here is the stack trace of that issue. I think the $order is no object.

`http://yii\base\ErrorException: Trying to get property of non-object in /var/www/local.sandoro.craft/vendor/kuriousagency/commerce-admin-orders/src/controllers/OrdersController.php:66 Stack trace: #0 /var/www/local.sandoro.craft/vendor/yiisoft/yii2/base/InlineAction.php(57): kuriousagency\commerce\adminorders\controllers\OrdersController->actionProducts() #1 /var/www/local.sandoro.craft/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/var/www/local.sandoro.craft/vendor/yiisoft/yii2/base/InlineAction.php:57}() #2 /var/www/local.sandoro.craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams() #3 /var/www/local.sandoro.craft/vendor/craftcms/cms/src/web/Controller.php(187): kuriousagency\commerce\adminorders\controllers\OrdersController->runAction() #4 /var/www/local.sandoro.craft/vendor/yiisoft/yii2/base/Module.php(528): kuriousagency\commerce\adminorders\controllers\OrdersController->runAction() #5 /var/www/local.sandoro.craft/vendor/craftcms/cms/src/web/Application.php(298): craft\web\Application->runAction() #6 /var/www/local.sandoro.craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction() #7 /var/www/local.sandoro.craft/vendor/craftcms/cms/src/web/Application.php(283): craft\web\Application->handleRequest() #8 /var/www/local.sandoro.craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest() #9 /var/www/local.sandoro.craft/web/index.php(21): craft\web\Application->run() #10 {main}`

**Comment by samuelbirch** [comment]
can you see in the request parameters if orderNumber is in there?

**Comment by MaximilianSchwarz** [comment]
orderNumber is {number}

**Comment by samuelbirch** [comment]
hmm, looks like the orderNumber is not being rendered as part of the return url.

Are you able to email your db and composer file to support @ kurious.agency and we'll take a look further.

**Comment by MaximilianSchwarz** [comment]
Send you the db and composer file.

**Comment by samuelbirch** [comment]
ok, looks like the cpUrl twig function is now encoding the twig params. I don't know when this changed?

This should be fixed in version 2.4.2 - can you let me know if it works for you?

**Comment by MaximilianSchwarz** [comment]
Thanks for the fast support. Now it works like a charm!
