### ISSUE TITLE
Custom price

### ISSUE THREAD

**Issue by MaximilianSchwarz** [KuriousAgency/commerce-admin-orders#6]
Is it possible to set a custom price for each product if i create the order with your plugin? Maybe placed under the price a checkbox and if i click on it enabel a input field for a custom price in this order?

**Comment by samuelbirch** [comment]
Hi, no its not possible currently. But its something we could look at adding to the roadmap.

**Comment by MaximilianSchwarz** [comment]
Okay. We are very interested in this function. Maybe you can write an email with an offerte? info@lecom24.com

**Comment by samuelbirch** [comment]
will do :)
